-- Tokyo session DST table for GET /api/symbols (doc 123).
-- season_cd 1 = summer session string, 2 = winter. Seed is winter 2020–2099.
-- Missing current row → HTTP 500 E_SERVER. Not M_SEASON; Postgres uses m_season.

CREATE TABLE m_season (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	season_cd INTEGER NOT NULL,
	start_at TIMESTAMP WITH TIME ZONE NOT NULL,
	end_at TIMESTAMP WITH TIME ZONE NOT NULL
);

INSERT INTO m_season (season_cd, start_at, end_at) VALUES
	(2, '2020-01-01 00:00:00+00', '2099-12-31 23:59:59+00');
