-- Saved chart layouts for docs 127–131 (REST exists; widget Save/Load is not wired).
-- Tenant is customer_no from the JWT. timestamp on GET is epoch of updated_at.

CREATE TABLE m_tv_chart_layout (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_no BIGINT NOT NULL,
	name VARCHAR(64) NOT NULL,
	content TEXT NOT NULL,
	ccypair_cd VARCHAR(6) NOT NULL,
	chart_type VARCHAR(8) NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
