-- Local login users (JWT stand-in for Peach S-01). Seeded at boot by AppUserSeedRunner.
-- demo/demo customer_no=1, demo2/demo2 customer_no=2.

CREATE TABLE m_app_user (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	username VARCHAR(64) NOT NULL,
	password_hash VARCHAR(100) NOT NULL,
	customer_no BIGINT NOT NULL,
	enabled BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uq_m_app_user_username UNIQUE (username)
);
