-- Design doc 121: Peach bar warehouse tables (plum_info → public in this demo).
-- Columns support BID/ASK/MID mapping (bid_* / ask_* OHLC).

CREATE TABLE t_chart_1 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_60 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_300 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_600 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_900 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_1800 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_3600 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_7200 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_14400 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_28800 (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_day (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_week (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);

CREATE TABLE t_chart_month (
	curpair_cd VARCHAR(6) NOT NULL,
	chart_datetime BIGINT NOT NULL,
	bid_open DOUBLE PRECISION NOT NULL,
	bid_high DOUBLE PRECISION NOT NULL,
	bid_low DOUBLE PRECISION NOT NULL,
	bid_close DOUBLE PRECISION NOT NULL,
	ask_open DOUBLE PRECISION NOT NULL,
	ask_high DOUBLE PRECISION NOT NULL,
	ask_low DOUBLE PRECISION NOT NULL,
	ask_close DOUBLE PRECISION NOT NULL,
	volume DOUBLE PRECISION NOT NULL DEFAULT 0,
	PRIMARY KEY (curpair_cd, chart_datetime)
);
