-- Chart theme/style templates for docs 136–139. Table name is plural (spec).
-- Same upsert pattern as V6. Frontend SaveLoadAdapter is not wired to this yet.

CREATE TABLE m_tv_chart_templates (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_no BIGINT NOT NULL,
	name VARCHAR(64) NOT NULL,
	content TEXT NOT NULL,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
	CONSTRAINT uq_m_tv_chart_templates_customer_name UNIQUE (customer_no, name)
);
